### ISSUE TITLE
IndexOutOfBoundsException after restoring instance state

### ISSUE THREAD

**Issue by kcorwin** [TonicArtos/SuperSLiM#39]
In my app, I was getting consistent crashes after rotating my device, due to an IndexOutOfBoundsException. The culprit seems to be LayoutManger's onRestoreInstanceState(), which does this: `mRequestPosition = ((SavedState) state).anchorPosition`.

In the case of rotating the device, my app rebuilds the cursor that backs the adapter peace-meal and calls notifyDataSetChanged() - but that happens after onRestoreInstanceState is called, so the max index ends up often being less than mRequestPosition.

The workaround of course is to not do that - so I'm being careful to wait until the adapter's state is fully restored before notifyDataSetChanged() is called - but I feel like SuperSLiM still probably shouldn't throw an IndexOutOfBoundsException in this case - though I'm not sure what the proper behavior should be (maybe mRequestPosition should be the maximum possible index if it ends up in this state?)

java.lang.IndexOutOfBoundsException: Invalid item position 46(46). Item count:45
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3345)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
    at com.tonicartos.superslim.LayoutState.getView(LayoutState.java:66)
    at com.tonicartos.superslim.SectionData.<init>(SectionData.java:38)
    at com.tonicartos.superslim.LayoutManager.determineAnchorPosition(LayoutManager.java:532)
    at com.tonicartos.superslim.LayoutManager.onLayoutChildren(LayoutManager.java:182)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)

**Comment by TonicArtos** [comment]
Yeah, SavedState.anchorPosition should be clipped to the range to prevent the exception.
