### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by deep7964** [TonicArtos/SuperSLiM#4]
Hello, 

I have downloaded your example. when I  try to run the example, it got crashed with Null Pointer exception. you can have a look on the crash log below.

01-07 13:51:55.819    1224-1224/com.tonicartos.superslim.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.tonicartos.superslim.example, PID: 1224
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
            at android.support.v7.widget.RecyclerView$LayoutManager.getPosition(RecyclerView.java:5017)
            at com.tonicartos.superslim.LayoutManager.computeVerticalScrollOffset(LayoutManager.java:700)
            at android.support.v7.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:1115)
            at android.view.View.canScrollVertically(View.java:12724)
            at android.support.v4.view.ViewCompatICS.canScrollVertically(ViewCompatICS.java:34)
            at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(ViewCompat.java:907)
            at android.support.v4.view.ViewCompat.canScrollVertically(ViewCompat.java:1192)
            at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:6322)
            at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:6301)
            at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:66)
            at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:228)
            at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:56)
            at android.view.View.onInitializeAccessibilityEvent(View.java:5415)
            at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5288)
            at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:20706)
            at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatIcs.java:117)
            at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:210)
            at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:358)
            at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:255)
            at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatJellyBean.java:82)
            at android.view.View.sendAccessibilityEventUnchecked(View.java:5273)
            at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:6831)
            at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:6857)
            at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:6051)
            at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:6164)
            at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2788)
            at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2788)
            at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2788)
            at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2788)
            at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2788)
            at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:7978)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3941)
            at android.view.ViewGroup.addView(ViewGroup.java:3733)
            at android.view.ViewGroup.addView(ViewGroup.java:3678)
            at android.support.v7.widget.RecyclerView$4.addView(RecyclerView.java:334)
            at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:79)
            at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:4955)
            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:4913)
            at com.tonicartos.superslim.LinearSectionLayoutManager.addView(LinearSectionLayoutManager.java:356)

**Comment by TonicArtos** [comment]
It looks like your adapter is providing views without layout parameters. Whilst I prefer this to not be the case, I agree that it is a bug for the library to crash on it.

**Comment by kcorwin** [comment]
Just a quick observation - I was also getting this exception, even when my views had layout params set. Turned out the problem is that my layoutParams.sectionFirstPosition in my views were incorrect - I was setting it to the index of the first (non-header) item in the section, when it's supposed to be the position of the section header itself.

**Comment by ab-helly** [comment]
I'm also getting this error in case if there is single item in the list

**Comment by TonicArtos** [comment]
This is a problem with the scroll indicator computation, which has been removed for now as it is bad, inaccurate, and will be wholly replaced after the section layout manager design changes.

**Comment by jesielin** [comment]
i encounter the similar problem:
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
            at android.view.ViewGroup$LayoutParams.<init>(ViewGroup.java:6403)
            at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6685)
            at android.support.v7.widget.RecyclerView$LayoutParams.<init>(RecyclerView.java:7420)
            at com.tonicartos.superslim.LayoutManager$LayoutParams.<init>(LayoutManager.java:1819)
            at com.tonicartos.superslim.GridSLM$LayoutParams.<init>(GridSLM.java:506)
            at com.tonicartos.superslim.GridSLM$LayoutParams.from(GridSLM.java:520)
            at com.zihexin.cwapp.activity.CityActivity$CountryAdapter.onBindViewHolder(CityActivity.java:111)
            at com.zihexin.cwapp.activity.CityActivity$CountryAdapter.onBindViewHolder(CityActivity.java:70)
            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4402)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3717)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
            at com.tonicartos.superslim.LayoutState.getView(LayoutState.java:44)
            at com.tonicartos.superslim.LayoutManager.layoutChildren(LayoutManager.java:1316)
            at com.tonicartos.superslim.LayoutManager.onLayoutChildren(LayoutManager.java:264)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.M
and i think i solve it
in onCreateViewHolder method, i use View.inflate(mContext,R.layout.item_country_content,null); before to get the itemView,and then i got the problem,finally,i change to this:
view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.item_country_content, viewGroup, false); and problem solved
just write here to help others

**Comment by TonicArtos** [comment]
@jesielin What you encountered is a bug. The configuration you had should had caused the layout manager to assign sensible default layout parameters to the item. #74.
