### ISSUE TITLE
NullPointerException with   function findFirstCompletelyVisibleItem () SectionData sd = null;

### ISSUE THREAD

**Issue by jmying** [TonicArtos/SuperSLiM#61]
Why    SectionData sd = null;  and use it 
 if (firstVisiblePosition == sd.firstPosition ||
                firstVisiblePosition > sd.firstPosition + 1) {
            // Header doesn't matter.
            return firstVisibleView;
        }  

java.lang.NullPointerException
            at com.tonicartos.superslim.LayoutManager.findFirstCompletelyVisibleItem(LayoutManager.java:103)
            at com.tonicartos.superslim.LayoutManager.isOverscrolled(LayoutManager.java:1368)
            at com.tonicartos.superslim.LayoutManager.fixOverscroll(LayoutManager.java:1031)
            at com.tonicartos.superslim.LayoutManager.onLayoutChildren(LayoutManager.java:323)

**Comment by TonicArtos** [comment]
Thanks.

**Comment by TonicArtos** [comment]
Actually, sd should be loaded with the section data if first visible view != null. There is something else going one.

**Comment by TonicArtos** [comment]
Oh I see, you are looking at the master branch. Yes, this is a work in progress, use the early_release_4 branch.
