### ISSUE TITLE
Sporadic NullPointerException in 0.4.5 on devices running KitKat

### ISSUE THREAD

**Issue by kcorwin** [TonicArtos/SuperSLiM#62]
Using the the 0.4.5 release. This is happening for some of our users, but unfortunately we are unable to reproduce it, so it's hard to say why it's happening. All reports are coming from devices running KitKat (4.4.2 and 4.4.4) and this apparently happens upon loading the activity (or shortly thereafter?).

This stack trace closely resembles https://github.com/TonicArtos/SuperSLiM/issues/4, but we're obviously using a more recent version.

I will update this issue as soon as I can find more useful information (sorry it's so vague!), but I thought I'd report it in the meantime in case anyone has ideas.

java.lang.NullPointerException
       at android.support.v7.widget.RecyclerView$LayoutManager.getPosition(SourceFile:5017)
       at com.tonicartos.superslim.LayoutManager.computeVerticalScrollOffset(SourceFile:555)
       at android.support.v7.widget.RecyclerView.computeVerticalScrollOffset(SourceFile:1115)
       at android.view.View.canScrollVertically(View.java:12016)
       at android.support.v4.view.ViewCompatICS.canScrollVertically(SourceFile:34)
       at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(SourceFile:907)
       at android.support.v4.view.ViewCompat.canScrollVertically(SourceFile:1192)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(SourceFile:6301)
       at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(SourceFile:66)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(SourceFile:228)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(SourceFile:56)
       at android.view.View.onInitializeAccessibilityEvent(View.java:5204)
       at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5077)
       at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:19417)
       at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(SourceFile:117)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(SourceFile:210)
       at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(SourceFile:358)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(SourceFile:255)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(SourceFile:82)
       at android.view.View.sendAccessibilityEventUnchecked(View.java:5062)
       at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:6615)
       at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:6641)
       at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:5876)
       at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:5949)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2539)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2539)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2539)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2539)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2539)
       at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:7434)
       at android.view.View.setFrame(View.java:15057)
       at android.view.View.layout(View.java:14944)
       at android.view.ViewGroup.layout(ViewGroup.java:4631)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14948)
       at android.view.ViewGroup.layout(ViewGroup.java:4631)
       at android.support.v4.view.ViewPager.onLayout(SourceFile:1594)
       at android.view.View.layout(View.java:14948)
       at android.view.ViewGroup.layout(ViewGroup.java:4631)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14948)
       at android.view.ViewGroup.layout(ViewGroup.java:4631)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14948)
       at android.view.ViewGroup.layout(ViewGroup.java:4631)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14948)
       at android.view.ViewGroup.layout(ViewGroup.java:4631)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5610)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5137)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by TonicArtos** [comment]
Just looking at the trace, it looks like the layout params are missing. Unless the view is null for some reason.

**Comment by TonicArtos** [comment]
Actually, thinking about it, it is most likely the view is null for some reason. I'll look at `computeVerticalScrollOffset` and see if there is some way for it to be null.

**Comment by TonicArtos** [comment]
Okay, I see how this is happening. I've forgotten to handle no items being attached yet. It looks like this actually only happens when items are being added to a layout with 0 children, which is why it is intermittent. From this I suppose you are setting an adapter and gradually adding items to it.

**Comment by TonicArtos** [comment]
Okay, I've made available a fix in v0.4.7-SNAPSHOT. It will fix the NPE. If there are no issues with it I'll put it out as a release tomorrow.

**Comment by kcorwin** [comment]
Excellent - thanks so much! We will give this a shot and report back either way.

**Comment by TonicArtos** [comment]
Okay, it is now out in v0.4.7.

**Comment by kcorwin** [comment]
I can confirm that this solved our problem. Thanks again!

**Comment by TonicArtos** [comment]
Yes, my own testing indicated would solve the problem, but having others corroborate is nice, especially since I've spread myself across four projects at the moment and I am not getting a lot of sleep.

Anyway, I've gotten the bulk of v0.5 done. I am working on testing the latest changes and I'll be putting up a new snapshot soon :)

Here is a [draft](../wiki/Release-Notes-for-v0.5.0) for the release notes. There is more to go in there yet, but you might like to take a look. Perhaps I can improve the layout or something.

**Comment by kcorwin** [comment]
Draft looks good so far. No complaints about the layout. For me personally, the most helpful thing is always examples - so any you can add (inline, in addition to the sample app) would make understanding the changes easier. (For example, with LayoutHelper.)

**Comment by TonicArtos** [comment]
Yeah, I plan on getting examples in there. Not sure it is practical for LayoutHelper as it is so very pervasive for SLM development.

e.g.
```java
interface LayoutHelper {
    int getChildCount(); // get recycler view child count.

    int getTop(View child); // get decorated top of child in slm coordinates.

    void measureChild(View child, int unavailableWidth, int unavailableHeight); // measures child for slm area.

    // and so much more…
}
```

I think that with regards to LayoutHelper, it is better to finish the SLM development guide.

**Comment by DennyWeinberg** [comment]
Same problem here. How can i fix this?
I am using 0.5.0-SNAPSHOT.
