### ISSUE TITLE
Index out of bounds exception sometimes when updating the recylcer view

### ISSUE THREAD

**Issue by ashmosaheb** [TonicArtos/SuperSLiM#65]
I am getting index out of bounds exception when I sometimes update the recycler view. All I am doing is

1) Replacing the dataset in the recycler adapter
2) Calling notifyDataSetChanged();

My getItemCount returns just returns the count of the dataset.

I am not sure if there is a bug in my code or not. I only started noticing this issue after around 0.4.4 (or some other release near that). Here is the crash log. I am using the latest version 0.4.7.

java.lang.IndexOutOfBoundsException: Invalid item position 12(12). Item count:12
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3614)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
       at com.tonicartos.superslim.LayoutState.getView(LayoutState.java:44)
       at com.tonicartos.superslim.LayoutManager.layoutChildren(LayoutManager.java:1306)
       at com.tonicartos.superslim.LayoutManager.onLayoutChildren(LayoutManager.java:262)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:561)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1594)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15671)
       at android.view.ViewGroup.layout(ViewGroup.java:5038)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by TonicArtos** [comment]
Hmm, I have an idea as to what could be causing this. Could you tell me if this happens only when the previous dataset has less items than the new one. Thanks.

**Comment by ashmosaheb** [comment]
Just been through all my crash logs, looks like this happens only when the new dataset has less items the previous one.

i.e. 

Fatal Exception: java.lang.IndexOutOfBoundsException
Invalid item position 26(26). Item count:19

Great work btw.

**Comment by TonicArtos** [comment]
You're welcome, and thank you for the bug report. This should be enough for me to fix the issue. I've got a couple of things on my plate right now, but I'll get to this within the day.

**Comment by ashmosaheb** [comment]
Thanks!

**Comment by TonicArtos** [comment]
Okay, I've got a fix for this in a snapshot. I'll put it out in a release in the next couple of days if there isn't an issue.

```groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile 'com.tonicartos.superslim:0.4.8-SNAPSHOT
}
```

**Comment by PatrickDattilio** [comment]
I just ran into this issue as well, the snapshot seems to have fixed it.

**Comment by TonicArtos** [comment]
:) Sorry that this bug happened. I should have caught it earlier when there was a related issue that was fixed. 

Anyway, running a few tests on my end indicates the bug should be fixed. I am just waiting a day or so in case anything else comes up.

**Comment by ashmosaheb** [comment]
Yeah the snapshot seems to fix it as well for me. I have not seen the issue since. Thanks.

**Comment by goessi01** [comment]
I still got this problem although I am using 0.4.9.1
It would be really nice if you could look into this.
Thanks in advance.

here is the crash log:

java.lang.IndexOutOfBoundsException: Invalid item position 5(5). Item count:5
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4004)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
at com.tonicartos.superslim.LayoutState.getView(LayoutState.java:44)
at com.tonicartos.superslim.GridSLM.computeHeaderOffset(GridSLM.java:53)
at com.tonicartos.superslim.LayoutManager.layoutChildren(LayoutManager.java:1330)
at com.tonicartos.superslim.LayoutManager.onLayoutChildren(LayoutManager.java:263)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2411)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2709)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15678)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5293)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by TonicArtos** [comment]
I ran into this myself recently. Unfortunately, this is actually a bug in
your adapter. However, I claim responsibility since how SuperSLiM interacts
with the adapter makes this hard to avoid. Basically, at the moment, you
have to update all items in your adapter when you add or remove items, as
the section positions has changed.

I need to change this interaction in the next major version, which I am
still working on.

**Comment by goessi01** [comment]
Thanks man! No worries.
Looking forward to it
