### ISSUE TITLE
NPE Crash when updating items and scrolling

### ISSUE THREAD

**Issue by rapid08** [TonicArtos/SuperSLiM#77]
I seem to get a NPE when signaling a NotifyItemChanged on a RecyclerView.Adapter and scrolling at the same time. See below for the stack trace.
# 

```
java.lang.NullPointerException: Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference
        at android.support.v7.widget.DefaultItemAnimator.runPendingAnimations(DefaultItemAnimator.java:152)
        at android.support.v7.widget.RecyclerView$2.run(RecyclerView.java:369)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:549)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
# 

What I've noticed:
1. This doesn't happen if I let the NotifyItemChanged events finish before scrolling. The RecyclerView appears to behave correctly in that there are no exceptions thrown.
2. Scrolling works if i remove the NotifyItemChanged notification.
3. This doesn't necessarily happen EVERY time I scroll so while I can't say that it definitely behaves correctly in point #1, I can say that I've ONLY seen it happen when scrolling and notifying item changed.
4. Doesn't seem to happen when NOT using SuperSLim and using vanilla Android LinearyLayoutManager.
5. Testing has been done with the exact same data set.
6. I'm using the GridSLM layout.

It looks like the ViewHolder is being discarded by the time animations are ran. I've double, triple, and quadrupled checked that I'm setting the correct FirstPosition, Count and ItemViewType so I don't believe its an issue in my implementation of the Adapter. 

Any ideas? Has anyone reported any similar or related issues?

**Comment by TonicArtos** [comment]
I am not surprised there are bugs here. I just haven't had time to get proper support for data changes into the library. I want to have it done in version 0.5, but you can see how long that is taking me.

**Comment by rapid08** [comment]
Sounds good. I do appreciate your work on this project and will keep an eye on further updates!

**Comment by TonicArtos** [comment]
It looks like there has been an update to RecyclerView that will help in fixing these kinds of problems.

**Comment by TonicArtos** [comment]
@rapid08 Sorry, it is taking me some time to get 0.5 done. In the mean time, does the old way of using notifyDataSetChanged work for you?

**Comment by DennyWeinberg** [comment]
I have the exact same problem... How to fix it?

**Comment by paradite** [comment]
@TonicArtos Hi, I can confirm that replacing `notifyItemChanged(position)` with `notifyDataSetChanged ` solves this issue for me.  
I also don't see any performance issues with using  `notifyDataSetChanged `.  
Initially if I scroll too fast, the error will happen. After using `notifyDataSetChanged `, I can scroll to arbitrary location and the image will "lazy load" correctly after a while.

**Comment by banking** [comment]
@TonicArtos I saw you close this issue on 24 Mar 2017. However I still get this problem when using v7-25.3.1, so this issue is fixed in which version of RecyclerView?

**Comment by 229106948** [comment]
I also have this issue in my project, It can be resolved by replacing notifyItemChanged with notifyDataSetChanged or replacing my version? my version is v7-25.0.1
